# Generated by Django 5.2.14 on 2026-05-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('status', models.CharField(choices=[('new', 'новое'), ('in_progress', 'в процессе'), ('done', 'сделано')], default='new', max_length=50)),
                ('end_date', models.DateField(null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Задача',
                'db_table': 'task',
            },
        ),
    ]
