# Generated by Django 5.2.14 on 2026-05-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('in_progress', 'в процессе'), ('done', 'сделано')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
