# Generated by Django 5.2.14 on 2026-06-15 10:31

import todo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_type_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, validators=[todo.validators.validate_title], verbose_name='Название'),
        ),
    ]
